version: '2'
services:
    travismysql-app:
        image: travismysql
        external_links:
            - travismysql-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travismysql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    travismysql-mysql:
        extends:
            file: mysql.yml
            service: travismysql-mysql
