version: '2'
services:
    travismysql-app:
        image: travismysql
        external_links:
            - travismysql-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/travisMysql
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    travismysql-postgresql:
        extends:
            file: postgresql.yml
            service: travismysql-postgresql
